"""Creacion de tabla direcciones y relacion con usuarios

Revision ID: f1e50d4f07ab
Revises: 0295119cabac
Create Date: 2025-04-03 21:48:17.967930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e50d4f07ab'
down_revision = '0295119cabac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calle', sa.Text(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('predeterminada', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direcciones')
    # ### end Alembic commands ###
