"""creacion de tablas

Revision ID: 69bb900b2094
Revises: 
Create Date: 2025-04-23 22:25:20.819169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bb900b2094'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canchas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('correo', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('ADMIN', 'CLIENTE', 'PERSONAL', name='tipousuario'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('reservas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('CREADO', 'PAGADO', 'CANCELADO', name='estadoreserva'), nullable=True),
    sa.Column('precio', sa.Float(precision=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cancha_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('usuarios')
    op.drop_table('canchas')
    # ### end Alembic commands ###
