# Generated by Django 5.2 on 2025-05-03 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_creacion_tabla_platos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cantidad', models.TextField()),
                ('platoId', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='gestion.plato')),
            ],
            options={
                'db_table': 'ingredientes',
            },
        ),
    ]
