# Generated by Django 5.2 on 2025-05-03 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_creacion_tabla_ingredientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
                ('platoId', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones', to='gestion.plato')),
            ],
            options={
                'db_table': 'preparaciones',
                'unique_together': {('orden', 'platoId')},
            },
        ),
    ]
