# Generated by Django 5.2 on 2025-05-09 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_modificacion_tabla_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='usuarioId',
            field=models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
