# Generated by Django 5.2 on 2025-05-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_creacion_relacion_usuario_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='esPublico',
            field=models.BooleanField(db_column='es_publico', default=True),
        ),
    ]
